### ISSUE TITLE
Milestone 2 - Creation of system state diagram (need update)

### ISSUE THREAD

**Issue by CarltonFoo** [TrickDKing/ICT2201-P5-6#15]
https://lucid.app/lucidchart/0df662ed-89c8-4678-aa49-c15c9ac2e957/edit?invitationId=inv_f19ec115-10ed-4544-954c-6b9a1d4bc031&page=ZEFmke8R9WP2#

**Comment by TrickDKing** [comment]
Creation of system state diagram has been completed. Now in refining process.

**Comment by TrickDKing** [comment]
Closed due to M2 Completion.
